name: trial_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.2.8
  bcrypt: ^1.1.3
  path_provider: ^2.0.15
  uuid: ^4.5.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  http: ^1.5.0
  geolocator: ^14.0.2
  live_currency_rate: ^1.0.8
  timezone: ^0.9.2
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^17.2.2
  flutter_svg: ^2.0.10+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - image/
